# Generated by Django 3.0.7 on 2020-06-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_code',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
    ]
