# Generated by Django 3.0.7 on 2020-06-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_game_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(choices=[('public', 'Anyone can join this game'), ('private', 'Only players with the code can join this game')], max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='GAME-NAME', max_length=32),
            preserve_default=False,
        ),
    ]
