# Generated by Django 3.0.7 on 2020-06-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200628_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_access',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.GameAccess'),
            preserve_default=False,
        ),
    ]
