# Generated by Django 3.0.7 on 2020-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_game_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
    ]
