# Generated by Django 3.0.7 on 2021-05-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200629_0029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamestatus',
            table='game_status',
        ),
    ]
